config/routes.rb
Eggplant::Application.routes.draw do

  root 'home#index'

      resources :users
      resources :submissions
      

      get 'account' => 'account#index'
      get 'account/:id/edit' => 'account#edit'
      patch '/charges/:id' => 'charges#create'
      resources :charges
      resources :campaigns
      get 'my' => 'campaigns#my'   
      post 'campaign/:id/win' => 'submissions#win', as:'win'
       

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
	validates_presence_of :price 
	validates_presence_of :description
	validates_presence_of :title
	validates_numericality_of :price, :on => :create

	belongs_to :user
	has_many :submissions
end

app/models/charge.rb
class Charge < ActiveRecord::Base
	belongs_to :user
	belongs_to :campaign
end

app/models/submission.rb
class Submission < ActiveRecord::Base
	belongs_to :user
	belongs_to :campaign
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :campaigns
	has_many :submissions
end

app/controllers/account_controller.rb
class AccountController < ApplicationController
	def index
		@campaigns = Userbin.current_user.campaigns
		@user = Userbin.current_user
		@submissions = Userbin.current_user.submissions
	end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController


def index
	@campaigns = Campaign.all
	@user = Userbin.current_user
end

def show
		@campaign = Campaign.find(params[:id])
		@user = Userbin.current_user
		if @user.id == @campaign.owner
			@c = 1
		else 
		end
		@submissions = @campaign.submissions
end

def new
	@campaign = Campaign.new
end

def edit
		@campaign = Campaign.find(params[:id])
		if @campaign.user == Userbin.current_user
			render 'edit'
		else
			redirect_to '/'
		end
end

def update
	@campaign = Campaign.find(params[:id])
		if @campaign.update_attributes(campaign_params)
  			redirect_to campaign_url
  		else
  			render 'edit'
  		end
end

def create
	@userbin = Userbin.user.email
	@campaign = Campaign.new(campaign_params)
	@campaign.user = Userbin.user
	@campaign.status = "Live"
	if @campaign.save
		redirect_to controller: :charges, action: :new, :id => @campaign
	else 
		render :new
	end
end

def destroy
	@campaign = Campaign.find(params[:id])
	if @campaign.user == Userbin.current_user
		Campaign.find(params[:id]).destroy
		redirect_to campaigns_path
	else
		redirect_to campaigns_path 
	end
	
end


private
def campaign_params
  params.require(:campaign).permit(:description, :owner, :title, :price, :status)
end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	def new
    
    @charge = Charge.new
    @campaign = Campaign.find(params[:id])
end

def create
  @campaign = Campaign.find(params[:campaign_id])
  
  
  #@campaign = Campaign.find(params[:id])
  # Amount in cents
  @amount = (@campaign.price * 100)


  customer = Stripe::Customer.create(
    :email => 'example@stripe.com',
    :card  => params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => 'Rails Stripe customer',
    :currency    => 'usd'
  )
  #not working perect
   #PUT A NOTICE IN HERE!!!!!!
rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to account_url
end

private
def campaign_params
  params.require(:charge).permit(:user_id, :campaign_id)
end




end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
	def index
		@submissions = Submission.all
		
	end

	def new
		@submission = Submission.new
	end


def win
    
    @submission = Submission.find(params[:id])

    @submission.winner = "yes"
    @submission.campaign.status = 'Finished'

    if        @submission.save
        if @submission.campaign.save    
        	redirect_to account_path
        end
    else

    
            render:new
    end

end
	

	def create
		@submission = Submission.new(submission_params)
		@submission.user = Userbin.user
		@submission.campaign = Campaign.find(params[:submission].permit(:cid)[:cid])
		if @submission.save
			redirect_to submission_url(@submission)
		else
			render:new
		end 
	end

	def edit
		@submission = Submission.find(params[:id])
		if @submission.user == Userbin.current_user
			render 'edit'
		else
			redirect_to '/'
		end
	end

	def update
		@submission = Submission.find(params[:id])
		if @submission.update_attributes(submission_params)
  			redirect_to submission_url
  		else
  			render 'edit'
  		end
	end

	def show
		@user = Userbin.current_user
		@submission = Submission.find(params[:id])
		if @user.submissions.include?(@submission)
			render 'show'
		else
			redirect_to '/'
		end
		@campaigns = Userbin.current_user.campaigns
	end

	def destroy
		Submission.find(params[:id]).destroy
		redirect_to submissions_path
	end


	private
	def submission_params
		params.require(:submission).permit(:content, :submitter, :winner, :title)
	end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def new
	
	end
	def index
		@user = Userbin.current_user
	end

	def create

	
	end

	def edit
		@user = User.find(params[:id])
				
	end 

	def update
		@user = User.find(params[:id])

		if @user.update_attributes(params[:user].permit(:username,:name))
			redirect_to '/account'
		else
			render 'edit'
		end
	end

	def destroy
		@user= User.find_by(params[:id])
		@user.destroy
		redirect_to '/'

	end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/campaigns/_my.html.erb
<div class="row">
	<fieldset class="small-4 small-offset-1 column">
	<legend>My Live Campaigns</legend>
		<% @campaigns.each do |c| %>
			<% if c.status == "Live" %>
				<ul>
					<li>
						<h5><%= c.title %>		</h5>
					</li>
					<li>
						<h5>$<%= c.price %>		</h5>
					</li>
					<li>
						<h5><%= link_to 'View', campaign_path(c.id), :class => "button [tiny]" %>		</h5>
					</li>
				</ul>
				<br>
			<% end %>						
		<% end %>
	</fieldset>

	<fieldset class="small-4 small-pull-1 column">
		<legend>My Finished Campaigns</legend>
		<% @campaigns.each do |c| %>
			<% if c.status == "Finished" %>	
				<ul>
					<li>
						<h5><%= c.title %></h5>
					</li>
					<li>
						<h5>$<%= c.price %></h5>
					</li>
					<li>
						<h5><%= link_to 'View', campaign_path(c.id), :class => "button" %></h5>
					</li>
				</ul>
			<% end %>				
		<% end %>
	</fieldset>
</div>	
	

app/views/campaigns/edit.html.erb
<div class="row">

 	<fieldset class="small-6 small-offset-3 columns">
	  	<legend>Edit</legend>
	  	<%= form_for @campaign do |f| %>
	  		<br>
	  		<%= f.label :title %>
	  		<%= f.text_field :title %>
	  		<%= f.label "Content" %>
	  		<%= f.text_area :description, size: "100x200" %>
	  		<%= f.submit "Save Changes", :class => "button" %>
				<% end %>
  	</fieldset>
  <div class="small-6 columns"></div>
</div>

app/views/campaigns/index.html.erb
<br>
		
	
<div class="row horiz">
	<fieldset class="small-10 small-offset-1 column">	
		<legend>Live Campaigns</legend>
		<ul class=" large-block-grid-3 mediumn-block-grid-3 large-block-grid-3">
			<% @campaigns.each do |c| %>
				<% if c.status == "Live" %>	
					<li>
						<fieldset>
								<legend><%= c.title %></legend>	
								<%= link_to 'View', campaign_path(c.id), :class => "button"  %>
								
								<h4>$<%= c.price %></h4>
						</fieldset>
					</li>
				<% end %>
			<% end %>
		</ul>		
	</fieldset>
</div>

app/views/campaigns/my.html.erb
<% if @user.campaigns.include?(@campaign) %>
				<% @campaign.each do |o| %>
					<%= o.title %>
				<% end %>
					<% else %>
				<% end %>

app/views/campaigns/new.html.erb
<br>
<div class="row">
  <fieldset class="small-6 small-offset-3 column">
    <legend>New Campaign</legend>
    <%= form_for @campaign, url: {action: "create"}, html: {class: "new_campaign_form"} do |f| %>
    	<p>Title</p>
      <%= f.text_field :title %>
      <p>Price (USD)</p>
      <%= f.text_field :price %>
      <p>Content</p>
      <%= f.text_area :description, size: "100x200" %>			
      <%= f.submit "Create", :class => "button" %>
    <% end %>
  </fieldset>
  <div class="small-5 column"></div>
</div>

app/views/campaigns/show.html.erb
<br>
<div class="row">
    <fieldset class="small-10 small-offset-1">
        <legend><%= @campaign.title %></legend>
        <h3>$<%= @campaign.price %></h3>
        <% if @user == @campaign.user %> 
            <% if @campaign.status == "Live" %> 
                <%= link_to 'Edit Campaign', edit_campaign_path(:id => @campaign.id), :class => "button"%>
            <% end %>
        <% end %>
        <p>This campaign is <span id="bigFont"><%= @campaign.status %></span></p>
        <p><%= @campaign.description %></p>
        <% if @campaign.status == "Live" %>
            <% if @user == @campaign.user %>
                    <h2>Submissions:</h2>
            <% end %>
        <% end %>
        <% if @campaign.status == "Live" %>        
            <% if @user.campaigns.include?(@campaign) %>
                <% @submissions.each do |o| %>
                    <h4><%= o.title %></h4>
                    <%= button_to "Winner", {:id => o.id , :controller => :submissions, action: "win"}, :class => "button" %>
                    <br>
                    <h4>Content:</h4>
                    <p class="pushleft"><%= o.content %></p>
                    <br>
                <% end %>
             <% end %>
        <% end %>
        <% if @campaign.status == "Finished" %>
            <h2>Winner:</h2>
        <% end %>
        <% if @campaign.status == "Finished" %>        
            <% if @user.campaigns.include?(@campaign) %>
                <% @submissions.each do |o| %>
                        <% if o.winner == "yes" %>      
                    <h4><%= o.title %></h4>
                    <br>
                    <h4>Content:</h4>
                    <p class="pushleft"><%= o.content %></p>
                    <br>
                   <% end %>
                <% end %>
             <% end %>
        <% end %> 
        <% if @campaign.status == "Live" %>
            <h3><%= link_to 'Submit Content', new_submission_path(:id => @campaign.id), :class => "button" %></h3>
        <% end %>
        <% if @user == @campaign.user %>
            <% if @campaign.status == "Live" %> 
                <%= button_to "Delete", {action:"destroy", id:@campaign}, :class => "button", method: :delete %>
            <% end %>
        <% end %>

    </fieldset>

app/views/charges/chargers.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/charges/create.html.erb
<div class="row">
	<fieldset class="small-6 small-offset-3">
			<legend>Thanks!</legend>
			<h4 >Thanks for your payment, please check your email for a receipt. </h4>
		<div ><%= link_to 'Home', account_path, :class => "button"  %></div>	
				
	</fieldset>
</div>

app/views/charges/index.html.erb
blah

app/views/charges/new.html.erb
<div class="row">
	<fieldset class="small-2 small-offset-5">
			<legend>Payment</legend>
			<%= form_tag charges_path do %>
				<h1>$<%= @campaign.price %><h1>

				<%= hidden_field_tag :campaign_id, params[:id]%>
				<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
	          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
	          data-description="The Best Content"
	          data-amount=<%= @campaign.price * 100 %> >
	 </script>
	 <% end %>
	</fieldset>
</div>

app/views/layouts/_header.html.erb
	<% if Userbin.user_logged_in? %>
	  <li>
	    <%= Userbin.current_user.email %>
	    <ul>
	      <li><%= link_to 'My Profile', account_path %></li>
	      <li><a rel="logout">Log out</a></li>
	    </ul>
	  </li>
	<% end %>

app/views/layouts/_landing.html.erb
<% if Userbin.user_logged_in? %>
    <% else %>

      <div class="row">
          
            <div class="small-12 columns navyBG">
              
              
              <br>
              <h3 class="whiteLetterPenBG">WORK ON YOUR PRODUCT.</h3>
                  <h3 class="whiteLetterPenBG">NOT YOUR CONTENT.</h3>
                  <br>
                  <h1 class="whiteLetterPenBG">EGGPLANT.</h1> 
                  <br>
                  <h3 class="whiteLetterPenBG">SIMPLE. FAST. RELIABLE.</h3>
                  <br>
            </div>
      </div>
   
    <div class="row">
      <div class="small-3 columns yellowBG greyFont">
            <h3>
            <br>
            The.
            <br>
            <br>
            </h3> 
      </div>
      <div class="small-3  columns yellowBG greyFont">
            <h3>
            <br>
            Best.
            <br>
            <br>
            </h3> 
        
      </div>
      <div class="small-3  columns yellowBG greyFont">
            <h3>
            <br>
           Content.
            <br>
            <br>
            </h3> 
        
      </div>
      <div class="small-3  columns yellowBG greyFont">
            <h3>
            <br>
            Ever.
            <br>
            <br>
            </h3> 
        
      </div>
    
    </div>
    <div class="row landingcontent" id="tealbottom">
      
      <div class="small-12 columns whiteLetterPenBG">
        <br>
        <br>
        <h6 class="whiteLetterPenBG">
            6 hours integrating your payment solution.  14 hours implementing your primary functionality.  3 hours working on CSS.  20 hours writing tests.
          <br>
          <br>
            You spend enough time writing your code, writing content is just another headache that you shouldn't  have to deal with.  Eggplant solves that.  Simply write down what content you need generated and how much you're willing to pay and let our professional writers handle the rest.
          <br>
          <br>
            But how does this magical system work you say? It's simple!  When you submit a campaign to Eggplant our invite only content creators each take a stab at the content you need and submit it for your review.  When you find the one you love you pick the winner.  You get the content and the winner gets paid. Simple, easy, headache free. Welcome to Eggplant.
        </h6>
        <br>
        <br>
      </div>  
    </div>
    <!-- Footer -->
 
        <% end %>
    <!-- End Footer -->

app/views/layouts/_nav.html.erb
<script>
  $(function() {
    $( "right" ).menu();
  });
  </script>



<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><a href="#">EGGPLANT</a></h1>
    </li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <% if Userbin.user_logged_in? %>
        <li>
          <%= link_to 'My Profile', account_path %>
        </li>
        <li>
          <%= link_to 'Campaigns', campaigns_path %>
        </li>
        <li>
          <%= link_to ' New Campaign', new_campaign_path %>
        </li>
        <li>
          <a rel="logout">Log out</a>
        </li>
    </ul>
  <% else %>
    <li><a rel="login">Log in</a></li>
    <li><a rel="signup">Sign up</a></li>
  <% end %>
    </ul>

    <!-- Left Nav Section -->
    <ul class="left">
      <% if Userbin.user_logged_in? %>
      <li >
          <a>Welcome <%= Userbin.current_user.email %></a>
      </li> 
      <% end %>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>GetEggplant</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.0/jquery.min.js"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/jquery-ui.min.js" type="text/javascript"></script>
  <script type="text/javascript" src="lib/jquery.ui.core.js"></script>
  <script type="text/javascript" src="lib/jquery.ui.widget.js"></script>
  <script type="text/javascript" src="jquery-ui-form.js"></script>
  <script type="text/javascript">
    $(function()
    {
      $("form").form();
    });
  </script>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render 'layouts/nav' %>
    <%= render 'layouts/landing' %>
    
    <%= yield %>
    <% javascript_include_tag "application" %>
    
      <footer class="row">
        <div class="large-12 columns"><hr>
            <div class="row">
 
              <div class="large-6 columns">
                  <p>© Eggplant.....and Randy</p>
              </div>
 
              <div class="large-6 small-12 columns">
                  <ul class="inline-list right">
                    <li><a href="#">The Team</a></li>
                    <li><a href="#">FAQ</a></li>
                    <li><a href="#">Legal</a></li>
                    
                  </ul>
              </div>
 
            </div>
        </div>
      </footer> 
  </body>

</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/submissions/_usersub.html.erb
<br>
<div class="row">
	<fieldset class="small-4 small-offset-1 column">
	<legend>My Submissions</legend>
		<% @submissions.each do |c| %>
			<ul>
				<li>
					<h4><%= c.title %></h4>
				</li>
				<li>
					<h5><%= link_to 'View', submission_path(c.id), :class => "button"  %></h5>
				</li>	
			</ul>
		<% end %>
	</fieldset>
</div>

app/views/submissions/edit.html.erb
<br>
<div class="row">
	<fieldset class="small-6 small-offset-3 column">
		<legend>Edit Submission</legend>
			<%= form_for @submission do |i| %>
			<%= i.label :title %>
			<%= i.text_field :title %>
			<%= i.label :content %>
			<%= i.text_area :content, size: "100x800" %>
			<%= i.hidden_field :cid, :value => params[:id]%>
			<%= i.submit  class: "button"   %>
		<% end %>

	</fieldset>
</div>
<div class="row">
	<div class="small-1 column "></div>
	<div class="small-11 column pushleft10">
		
	</div>
</div>

app/views/submissions/new.html.erb
<div class="row">	
	<fieldset class="small-6 small-offset-3 column">
		<legend>Submit Content</legend>
			<%= form_for @submission do |i| %>
			<%= i.label :title %>
			<%= i.text_field :title %>
			<%= i.label :content %>
			<%= i.text_area :content, size: "100x800" %>
			<%= i.hidden_field :cid, :value => params[:id]%>
			<%= i.submit class: "button"  %>
		<% end %>
	</fieldset>
</div>

app/views/submissions/show.html.erb
<div class="row">
	<fieldset class="small-10 small-offset-1 column">
		<legend><%= @submission.title %></legend>	
		<h3>Campaign: <%= @submission.campaign.title %>  </h3>
		<h3>Content:</h3>
		<h5><%= @submission.content %></h5>
		<% if @submission.campaign.status == "Live" %>		
						<h4><%= link_to 'Edit', edit_submission_path, :class => "button" %></h4>
						<%= button_to "Delete", {action:"destroy", id:@submission}, :class => "button" ,method: :delete %>
				    <h4><%= link_to 'Back', account_path, :class => "button" %></h4>
			<% end %>
	</fieldset>
</div>

app/views/users/edit.html.erb
<div class="row">
 	<fieldset class="small-6 small-offset-3 columns">
 		<legend>Edit</legend>
 		<%= form_for @user do |user| %>
  		<h3><%= user.label :name %></h3>
  		<%= user.text_field :name %>
  		<h4><%= user.submit class: "button" %></h4>
  	<% end %>
  </fieldset>
</div>